StudentManagementApp/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from StudentManagementApp import views
from StudentManagementSystem import settings

urlpatterns = [
                  path('', views.view_login, name='login'),
                  path('register/', views.view_register),
                  path('doLogin/', views.doLogin, name='doLogin'),
                  path('forgot-password/<str:name>', views.resetPassword, name='resetPassword'),
                  path('resetPassword/reset/', views.reset, name='reset'),
                  path('home/', views.loadHome, name='home'),
                  path('home/table/<int:id>', views.loadTable, name='table'),
                  path('home/logout/', views.doLogout, name='logout'),
                  path('home/blank/', views.blank),
                  path('404/', views.load404, name='404'),
                  path('home/index/<int:id>', views.load_index, name='index'),
                  path('adminHome/', views.loadAdmin, name='adminHome'),
                  path('adminHome/addStu/', views.adminAddStu, name='adminAddStu'),
                  path('adminHome/addStu/complete/', views.adminComStu, name='completeAddStu'),
                  path('adminHome/addCourse/', views.adminAddCourse, name='addCourse'),
                  path('adminHome/addCourse/complete/', views.adminComCourse, name='completeAddCourse'),
                  path('adminHome/addStaff/', views.adminAddStaff, name='addStaff'),
                  path('adminHome/addStaff/complete/', views.adminComStaff, name='completeAddStaff'),
                  path('adminHome/manageCourse', views.adminMgrCourse, name='manageCourse'),
                  path('adminHome/manageStu', views.adminMgrStu, name='manageStu'),
                  path('staffHome/', views.staffHome, name='staffHome'),
                  path('adminHome/addClass/', views.adminAddClass, name='adminAddClass'),
                  path('adminHome/addClass/complete', views.adminComClass, name='completeAddClass'),
                  path('adminHome/ManageStaff', views.adminMgrStaff, name='adminMgrStaff'),
                  path('adminHome/ManageStaff/manage/<int:pk>', views.AdminStaffMgrView, name='adminStaffMgr'),
                  path('adminHome/manageCourse/manage/<int:pk>', views.AdminCourseMgrView.as_view(),
                       name='adminCourseMgr'),
                  path('adminHome/manageClass/', views.adminClassMgr, name='adminMgrClass'),
                  path('adminHome/arrangeCourse/', views.adminArrangeCourse, name='adminArrangeCourse'),
                  path('adminHome/arrangeCourse/complete', views.adminComArrCourse, name='adminComArrCourse'),
                  path('adminHome/ManageStaff/manage/edit/<int:id>/', views.adminComMgrStaff,
                       name='adminComMgrStaffEdit'),
                  path('staffHome/aboutStu/<int:id>', views.staffAboutStu, name='staffAboutStu'),
                  path('staffHome/editStu/<int:id>', views.staffEditStu, name='staffEditStu'),
                  path('staffHome/about/<int:id>', views.staffAboutMe, name='staffAboutMe'),
                  path(
                      'staffHome/editStu/<int:id>/<int:id1>/<int:id2>/coursename=<str:coursename>/classname=<str'
                      ':classname>',
                      views.staffEditScore, name='staffEditScore'),
                  path('staffHome/edidStu/score/', views.staffEditStuScore, name='staffEditStuScore'),
                  path('adminHome/export_to_excel', views.stuExport, name='stuExport'),
                  path('adminHome/searchStu/', views.adminSearchStu, name='adminSearchStu'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

StudentManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('StudentManagementApp.urls'))
]

StudentManagementApp/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractUser):
    user_id = models.CharField(primary_key=True, max_length=255, verbose_name='用户ID')
    phone_number = models.IntegerField(verbose_name='手机号')
    in_school_time = models.DateTimeField(auto_now_add=True, verbose_name='报到时间')
    user_type_data = ((1, "Admin"), (2, "Staff"), (3, "Student"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)
    REQUIRED_FIELDS = ['user_id', 'phone_number', 'email']

    class Meta:
        ordering = ('user_id',)


# Create your models here.
class Student(models.Model):
    id = models.CharField(primary_key=True, max_length=255, verbose_name='学号')
    # name = models.CharField(max_length=255, help_text='姓名', verbose_name='学生姓名')
    gender = models.CharField(max_length=4, choices=[('男', '男性'), ('女', '女性')], help_text='性别', verbose_name='性别')
    # email = models.EmailField()
    # passwd = models.CharField(max_length=255)
    address = models.TextField(verbose_name='地址')
    # 所在班级
    inClass = models.ForeignKey('StuClass', on_delete=models.CASCADE, null=True, blank=True, verbose_name='班级')

    pic = models.FileField(verbose_name='个人照片')
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, verbose_name='账号')
    dept = models.CharField(max_length=255, verbose_name='院系', default='信工')

    class Meta:
        verbose_name = '学生'
        verbose_name_plural = '学生'
        ordering = ('id',)

    def __str__(self):
        return self.admin.username


class Staff(models.Model):
    id = models.CharField(primary_key=True, max_length=255, verbose_name='教师号')
    # name = models.CharField(max_length=255, help_text='姓名', verbose_name='学生姓名')
    gender = models.CharField(max_length=4, choices=[('男', '男性'), ('女', '女性')], help_text='男或女', verbose_name='性别')
    # email = models.EmailField()
    # passwd = models.CharField(max_length=255)
    address = models.TextField(verbose_name='地址')
    # phone_number = models.IntegerField(verbose_name='手机号')
    pic = models.FileField(verbose_name='个人照片')
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, verbose_name='账号')
    courses = models.ManyToManyField('Course', verbose_name='课程')
    dept = models.CharField(max_length=255, verbose_name='院系', default='信工')

    class Meta:
        verbose_name = '教员'
        verbose_name_plural = '教员'
        ordering = ('id',)


class Admin(models.Model):
    id = models.CharField(primary_key=True, max_length=255, verbose_name='学号')
    # name = models.CharField(max_length=255, help_text='姓名', verbose_name='学生姓名')
    gender = models.CharField(max_length=4, choices=[('男', '男性'), ('女', '女性')], help_text='性别', verbose_name='性别')
    # email = models.EmailField()
    # passwd = models.CharField(max_length=255)
    address = models.TextField(verbose_name='地址')
    # phone_number = models.IntegerField(verbose_name='手机号', default=1)
    pic = models.FileField(verbose_name='个人照片')
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    class Meta:
        verbose_name = '教务处'
        verbose_name_plural = '教务处'


class Course(models.Model):
    name = models.CharField(max_length=255, verbose_name='课程名称', unique=True)
    credit = models.IntegerField(verbose_name='学分')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = "课程"
        ordering = ('id',)


class StuClass(models.Model):
    class_id = models.CharField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)
    subject = models.CharField(verbose_name='专业', max_length=255, default='软件工程')

    class Meta:
        verbose_name = '班级'
        verbose_name_plural = '班级'
        ordering = ('class_id',)


class Study(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, blank=True, null=True)
    score = models.IntegerField(verbose_name='分数')

    class Meta:
        verbose_name = '修习'
        verbose_name_plural = '修习'
        ordering = ('id',)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(admin=instance, id=instance.user_id)
        if instance.user_type == 2:
            Staff.objects.create(admin=instance, id=instance.user_id)
        if instance.user_type == 3:
            Student.objects.create(admin=instance, id=instance.user_id)


@receiver(post_save, sender=CustomUser)
def save_suer_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.id = instance.admin.admin_id
        instance.admin.save()
    if instance.user_type == 2:
        instance.staff.id = instance.staff.admin_id
        instance.staff.save()
    if instance.user_type == 3:
        instance.student.id = instance.student.admin_id
        instance.student.save()

StudentManagementApp/templates/adminAddStaff.html
{% extends 'base_template/adminBase.html' %}

{% block main_content %}
    <div class="row-cols-auto">添加教员</div>
    <form action="{% url 'completeAddStaff' %}" method="post" id="demo-form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="职工号" name="username">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="姓名" name="name">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="email" class="form-control" placeholder="邮箱" name="email">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="password" class="form-control" placeholder="密码" name="password">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="手机号" name="phone">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="住址" name="address">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <select class="form-control" name="sex">
                <option value="男">男</option>
                <option value="女">女</option>
            </select>
        </div>

        <div class="input-group mb-3">
            <input type="file" class="form-control" placeholder="照片" name="profile_pic">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="院系" name="dept">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- /.col -->
            <div class="col-12">
                <button type="submit" class="btn btn-primary btn-block">完成注册</button>
            </div><!-- /.col -->

        </div>
        <div class="row">
            {% if messages %}
                <div class="col-12">
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </form>
{% endblock main_content %}

StudentManagementApp/templates/adminAddStu.html
{% extends 'base_template/adminBase.html' %}

{% block main_content %}
    <div class="row-cols-auto">添加学生</div>
    <form action="complete/" method="post" id="demo-form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="必填：学号，只能是数字" name="username">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="必填：姓名" name="name">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="email" class="form-control" placeholder="必填：邮箱" name="email">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="password" class="form-control" placeholder="必填：密码" name="password">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="必填：手机号" name="phone">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-phone"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="必填：住址" name="address">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>
        {#        <div class="input-group mb-3">#}
        {#            <select class="form-control" name="course">#}
        {#                {% for course in courses %}#}
        {#                    <option value="{{ course.id }}">{{ course.name }}</option>#}
        {#                {% endfor %}#}
        {#            </select>#}
        {##}
        {#            <div class="input-group-append">#}
        {#                <div class="input-group-text">#}
        {#                    <span class="fas fa-lock"></span>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}
        <div class="input-group mb-3">
            <select class="form-control" name="sex">
                <option value="男">男</option>
                <option value="女">女</option>
            </select>

            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>

        <div class="input-group mb-3">
            <input type="file" class="form-control" placeholder="照片" name="profile_pic">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>

        <div class="input-group mb-3">
            <input type="date" class="form-control" placeholder="报到时间" name="time" value="{{ now }}">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                </div>
            </div>
        </div>
        <div class="input-group mb-3">
            <select class="form-control" name="choice">
                {% for choice in choices %}
                    <option value="{{ choice.class_id }}">{{ choice.name }}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>

        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="必填：院系" name="dept">
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- /.col -->
            <div class="col-12">
                <button type="submit" class="btn btn-primary btn-block">完成注册</button>
            </div><!-- /.col -->

        </div>
        <div class="row">
            {% if messages %}
                <div class="col-12">
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </form>
{% endblock main_content %}

StudentManagementApp/templates/adminArrangeCourse.html
{% extends 'base_template/adminBase.html' %}
{% load static %}
{% load mathfilters %}
{% block main_content %}
    <div class="row-cols-auto">安排课程</div>
    <div class="mb-3">
    </div>
    <form action="{% url 'adminComArrCourse' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <label>课程 &nbsp;&nbsp;</label>
            <select class="form-control" name="course" id="course">
                {% for course in courses %}
                    <option value="{{ course.id }}">{{ course.name }}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>

        <div class="input-group mb-3">
            <label>班级 &nbsp;&nbsp;</label>
            <select class="form-control" name="class" id="class">
                {% for class in classes %}
                    <option value="{{ class.class_id }}">{{ class.name }}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>

        <div class="input-group mb-3">
            <label>教员 &nbsp;&nbsp;</label>
            <select class="form-control" name="staff" id="staff">
                {% for staff in staffs %}
                    <option value="{{ staff.id }}">{{ staff.admin.username }}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
                <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                </div>
            </div>
        </div>

        <div class="row">
            {% if messages %}
                <div class="col-12">
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="row">
            <!-- /.col -->
            <div class="col-12">
                <button type="submit" class="btn btn-primary btn-block">确认</button>
            </div><!-- /.col -->
        </div>

    </form>

{% endblock main_content %}

StudentManagementApp/templates/adminCourseMgr.html
{% extends 'base_template/adminBase.html' %}
{% load static %}
{% block main_content %}


{% endblock main_content %}

StudentManagementApp/templates/adminMgrCourse.html
{% extends 'base_template/adminBase.html' %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">课程详情</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap table-bordered">
                                <thead>
                                <tr style="font-size: 30px">
                                    <th>序号</th>
                                    <th style="font-size: 25px">ID</th>
                                    <th style="font-size: 25px">课程名</th>
                                    <th style="font-size: 25px">学分</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for course in courses %}
                                    <tr class="table-responsive-sm table-light" style="font-size: 20px; ">
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ course.id }}</td>
                                        <td>{{ course.name }}</td>
                                        <td>{{ course.credit }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->


{% endblock main_content %}

StudentManagementApp/templates/staffAboutStu.html
{% extends 'base_template/staffBase.html' %}
{% load static %}

{% block main_content %}
    <div class="table-responsive table mt-2" id="dataTable" role="grid"
         aria-describedby="dataTable_info">
        <table class="table my-0 table-bordered table-responsive" id="dataTable">
            <thead class="table-primary" align="center">
            <tr>
                <th>班级</th>
                <th>课程</th>
                <th>学生</th>
                <th>成绩</th>
            </tr>
            </thead>
            <tbody align="center">
            {% for courses in staff.courses.all %}
                {% for study in courses.study_set.all %}
                    <tr>
                        <td>{{ study.student.inClass.name }}</td>
                        <td>{{ courses.name }}</td>
                        <td>{{ study.student.admin.username }}</td>
                        {% if study.score < 0 %}
                            <td>尚未考试</td>
                        {% else %}
                            <td>{{ study.score }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                <tr>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>


{% endblock main_content %}

StudentManagementApp/templates/staffEditStu.html
{% extends 'base_template/staffBase.html' %}
{% load static %}

{% block main_content %}
    <div class="card shadow">
        <div class="card-header py-3"><p class="text-primary m-0 fw-bold">{{ user.username }}</p></div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 text-nowrap">
                    <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable"></div>
                </div>
                <div class="col-md-6">
                    <div class="text-md-end dataTables_filter" id="dataTable_filter"></div>
                </div>
            </div>
            <div class="table-responsive table mt-2" id="dataTable" role="grid"
                 aria-describedby="dataTable_info">


                <table class="table text-nowrap table-hover table-bordered" id="dataTable">
                    <thead>
                    <tr class="text-center">
                        <th>班级</th>
                        <th>课程</th>
                        <th>学号</th>
                        <th>姓名</th>
                        <th>成绩</th>
                        <th>修改</th>
                    </tr>
                    </thead>
                    <tbody align="center">

                    {% for courses in staff.courses.all %}

                        {% for study in courses.study_set.all %}
                            <tr>
                                <td>{{ study.student.inClass.name }}</td>
                                <td>{{ courses.name }}</td>
                                <td>{{ study.student.id }}</td>
                                <td>{{ study.student.admin.username }}</td>
                                {% if study.score < 0 %}
                                    <td>尚未考试</td>
                                {% else %}
                                    <td>{{ study.score }}</td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'staffEditScore' id=study.student.id id1=courses.id id2=staff.id coursename=courses.name classname=study.student.inClass.name %}"
                                       class="btn btn-danger btn-google">修改</a></td>
                            </tr>
                        {% endfor %}
                    {% endfor %}


                    </tbody>
                </table>


                <div>
                    {% if messages %}
                        <div class="col-12">
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                    <div class="alert alert-danger"
                                         style="margin-top:10px">{{ message }}</div>
                                {% endif %}
                                {% if message.tags == 'success' %}
                                    <div class="alert alert-success"
                                         style="margin-top:10px">{{ message }}</div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock main_content %}